create graphs for paper with netgraph package
JulianKarlBauer/mechkit pull request #33
Opened 2022-02-16 11:39 UTC by jonashund

2022-02-16 11:47 UTC, JulianKarlBauer commented
Nice, thanks! We should definitely use your nice graphic inside the paper!

2022-02-16 14:24 UTC, JulianKarlBauer requested changes

2022-02-16 14:24 UTC, JulianKarlBauer commented on paper/paper.md
> +that facilitate common tasks within tensor algebra and tensor notation.
```suggestion
`mechkit` contains methods and operators
that simplify common tasks - especially in the area of tensor algebra and tensor notation.
```

2022-02-16 14:24 UTC, JulianKarlBauer commented on paper/paper.md
> +sources is strived for. **For validation or just for fun?**
```suggestion
sources is aimed at, for validation reasons.
```

2022-02-16 14:24 UTC, JulianKarlBauer commented on paper/paper.md
> +Apart from didactic advantages **I don't get what you want to say here. Suggestion in line 65.**, this procedure causes problems for
Thanks for feedback, let's talk about this, but please remove your changes.
Why are all these lines highlighted, although you did just add a comment?
Please do not change line endings.

2022-02-16 14:24 UTC, JulianKarlBauer commented on paper/paper.md
> +This presents a major obastacle with regard to the exchange and reliability of research code as well as the interpretation and comparison of results.
nice, thanks

2022-02-16 14:24 UTC, JulianKarlBauer commented on paper/paper.md
Please avoid no-content-changes and remove comments here, you would change the authorship...

2022-02-16 14:24 UTC, JulianKarlBauer commented on paper/paper.md
> +and numerical solution methods for boundary value problems,
nice

2022-02-16 14:24 UTC, JulianKarlBauer commented on paper/paper.md
> +As an example, one may consider the description of the mechanical properties of a
thanks

2022-02-16 14:24 UTC, JulianKarlBauer commented on paper/paper.md
> -isotropic material, which can be combined to a fourth-order elasticity tensor.
I would like to stick to `a`

2022-02-16 14:24 UTC, JulianKarlBauer commented on paper/paper.md
> +increases drastically **exponentially?** with an increasing number of notations.
```suggestion
increases drastically with an increasing number of notations.
```

2022-02-16 14:26 UTC, JulianKarlBauer commented
Hi Jonas, thanks for adding this valuable contribution.
Would you mind working on these few requested changes?

A general remark:
Please do not include comments into the source.
You can use githubs comment features within merge-request, see, e.g., [help](https://docs.gitlab.com/ee/user/project/merge_requests/reviews/)

2022-02-18 07:45 UTC, jonashund commented
Hi Julian,

I gave the review tutorial a quick read and will try the function later.
I'd also like to appear in the authors list.
Is my merge request now clean and ready to merge?

2022-02-18 09:04 UTC, JulianKarlBauer approved these changes

2022-02-18 09:05 UTC, merged